"""Core id -> what libretro says that core is. GENERATED -- do not edit.

    python scripts/render_core_info.py

305 cores, read from `libretro/libretro-core-info` on 2026-08-01. That
repository is MIT, verified by reading its own COPYING rather than
GitHub's summary of it.

Each row carries only what an operator choosing a core needs, and every
value is libretro's own words:

  display       the core's `display_name` ("Nintendo - SNES / SFC (Snes9x)")
  system        `systemname` ("Super Nintendo Entertainment System")
  manufacturer  `manufacturer` ("Nintendo")
  license       `license` -- the CORE's licence, not this plugin's, and
                they genuinely differ: Snes9x says "Non-commercial"
  extensions    `supported_extensions` ("smc|sfc|swc|fig|bs|st")
  firmware      the BIOS files the core needs, **excluding** the ones
                libretro marks `firmwareN_opt = "true"`
  databases     the `database` field split on "|" -- libretro's own
                platform names, which is how a core says what it is for

A key is absent rather than empty when libretro says nothing, so
`row.get("system")` returning None means "not stated upstream".

This replaced a hand-kept 106-row table that answered `None` for the
other 112 cores the buildbot ships. It is a snapshot and will go stale in
one direction: a core libretro adds appears here as unknown until this is
regenerated, which is a missing label rather than a wrong one. The `.info`
file for the core an operator actually installs is fetched live at install
time and is never this snapshot.
"""


CORE_INFO: dict[str, dict] = {
    '2048': {"display": "2048", "system": "2048 Game Clone", "manufacturer": "N/A", "license": "Public Domain", "databases": ["2048"]},
    '3dengine': {"display": "Test Core - 3D Engine", "system": "3D Engine", "manufacturer": "Libretro", "license": "GPLv3", "extensions": "png|jpg|mtl|obj", "databases": ["null"]},
    '81': {"display": "Sinclair - ZX 81 (EightyOne)", "system": "ZX81", "manufacturer": "Sinclair", "license": "GPLv3", "extensions": "p|tzx|t81", "databases": ["Sinclair - ZX 81"]},
    'DoubleCherryGB': {"display": "Nintendo - Game Boy / Color (DoubleCherryGB)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "cgb|dmg|gb|gbc|sgb", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'FreeIntvTSOverlay': {"display": "Mattel Intellivision (FreeIntvTSOverlay)", "system": "Intellivision", "manufacturer": "Mattel", "license": "GPLv3", "extensions": "intv|bin|rom|zip", "firmware": ["grom.bin"], "databases": ["Mattel - Intellivision"]},
    'a5200': {"display": "Atari - 5200 (a5200)", "system": "Atari 5200", "manufacturer": "Atari", "license": "GPLv2", "extensions": "a52|bin", "databases": ["Atari - 5200"]},
    'advanced_tests': {"display": "Test Core - Advanced Test", "system": "Advanced Test Core", "manufacturer": "N/A", "license": "MIT"},
    'amiarcadia': {"display": "Arcadia 2001 / Interton VC 4000 (AmiArcadia)", "system": "Arcadia 2001", "manufacturer": "Emerson|Interton|Elektor|Zaccaria", "license": "Non-commercial", "extensions": "bin|tvc", "databases": ["Elektor - TV Games Computer", "Emerson - Arcadia 2001", "Interton - VC 4000"]},
    'amiberry': {"display": "Commodore - Amiga (Amiberry)", "system": "Amiga", "manufacturer": "Commodore", "license": "GPLv3", "extensions": "adf|adz|dms|fdi|ipf|hdf|hdz|lha|slave|info|cue|ccd|nrg|mds|iso|uae", "firmware": ["kick34005.A500", "kick37350.A600", "kick40068.A1200"], "databases": ["Commodore - Amiga", "Commodore - CD32", "Commodore - CDTV"]},
    'anarch': {"display": "Anarch", "system": "Anarch", "manufacturer": "N/A", "license": "CC0"},
    'applewin': {"display": "Apple II (AppleWin)", "system": "II", "manufacturer": "Apple", "license": "GPLv2", "extensions": "bin|do|dsk|nib|po|gz|woz|zip|2mg|2img|iie|apl|hdv|yaml|m3u", "databases": ["Apple - II"]},
    'ardens': {"display": "Arduboy (Ardens)", "system": "Arduboy", "manufacturer": "Arduboy", "license": "MIT", "extensions": "hex|arduboy", "databases": ["Arduboy Inc - Arduboy"]},
    'arduous': {"display": "Arduboy (Arduous)", "system": "Arduboy", "manufacturer": "Arduboy", "license": "GPLv3", "extensions": "hex", "databases": ["Arduboy Inc - Arduboy"]},
    'atari800': {"display": "Atari - 400/800/600XL/800XL/130XE/5200 (Atari800)", "system": "Atari 8-bit Family", "manufacturer": "Atari", "license": "GPLv2", "extensions": "xfd|atr|dcm|cas|bin|a52|zip|atx|car|rom|com|xex|m3u", "databases": ["Atari - 5200", "Atari - 8-bit Family"]},
    'azahar': {"display": "Nintendo - 3DS (Azahar)", "system": "3DS", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "3ds|3dsx|z3dsx|elf|axf|cci|zcci|cxi|zcxi|app", "databases": ["Nintendo - Nintendo 3DS"]},
    'b2': {"display": "Acorn - BBC Micro (b2)", "system": "BBC Micro", "manufacturer": "Acorn", "license": "GPLv3", "extensions": "ssd|dsd"},
    'bennugd': {"display": "Bennu Game Development", "system": "Bennu Game Development", "manufacturer": "SplinterGU", "license": "GPLv3", "extensions": "dcb|dat|exe", "databases": ["BennuGD"]},
    'bk': {"display": "Elektronika - BK-0010/BK-0011(M)", "system": "BK-0010/BK-0011(M)", "license": "BSD", "extensions": "bin", "databases": ["BK-0010/BK-0011"]},
    'blastem': {"display": "Sega - Mega Drive - Genesis (BlastEm)", "system": "Sega Genesis", "manufacturer": "Sega", "license": "GPLv3", "extensions": "md|bin|smd|gen|68k|sgd", "databases": ["Sega - Mega Drive - Genesis"]},
    'bluemsx': {"display": "MSX/SVI/ColecoVision/SG-1000 (blueMSX)", "system": "MSX/SVI/ColecoVision/SG-1000", "manufacturer": "Spectravideo|Philips|Al Alamiah|Sony|Sanyo|Mitsubishi|Toshiba|Hitachi|Panasonic|Canon|Casio|Pioneer|Fujitsu|Yamaha|JVC|Kyocera|GoldStar|Samsung|Daewoo|Gradiente|Sharp|Talent|NTT|ACVS/CIEL|DDX|AGE Labs", "license": "GPLv2", "extensions": "rom|ri|mx1|mx2|dsk|col|sg|sc|sf|cas|m3u", "firmware": ["Databases/msxromdb.xml", "Machines/Shared Roms/MSX.rom"], "databases": ["Microsoft - MSX", "Microsoft - MSX2", "Coleco - ColecoVision", "Sega - SG-1000", "Spectravideo - SVI-318 - SVI-328"]},
    'bnes': {"display": "Nintendo - NES / Famicom (bnes)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "nes", "databases": ["Nintendo - Nintendo Entertainment System"]},
    'boom3': {"display": "Doom 3 (boom3)", "system": "Doom 3 Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pk4", "databases": ["Doom 3"]},
    'boom3_xp': {"display": "Doom 3: Resurrection of Evil (boom 3 xp)", "system": "Doom 3 XP Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pk4", "databases": ["Doom 3"]},
    'boytacean': {"display": "Nintendo - Game Boy / Color (Boytacean)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "Apache-2.", "extensions": "gb|gbc", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'bsnes-jg': {"display": "Nintendo - SNES / SFC (bsnes-jg)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "smc|sfc|st|gb|gbc|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes2014_accuracy': {"display": "Nintendo - SNES / SFC (bsnes 2014 Accuracy)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|bml|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes2014_balanced': {"display": "Nintendo - SNES / SFC (bsnes 2014 Balanced)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|bml|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes2014_performance': {"display": "Nintendo - SNES / SFC (bsnes 2014 Performance)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|bml|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes_cplusplus98': {"display": "Nintendo - SNES / SFC (bsnes C++98 (v085))", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes_hd_beta': {"display": "Nintendo - SNES / SFC (bsnes-hd beta)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "smc|sfc|swc|fig|gb|gbc|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes': {"display": "Nintendo - SNES / SFC (bsnes)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "smc|sfc|swc|fig|gb|gbc|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes_mercury_accuracy': {"display": "Nintendo - SNES / SFC (bsnes-mercury Accuracy)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|bml|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes_mercury_balanced': {"display": "Nintendo - SNES / SFC (bsnes-mercury Balanced)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|bml|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'bsnes_mercury_performance': {"display": "Nintendo - SNES / SFC (bsnes-mercury Performance)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|bml|gb|gbc|st|bs", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'cannonball': {"display": "Cannonball", "system": "Outrun Game Engine", "manufacturer": "Sega", "license": "Non-commercial", "extensions": "game|88", "databases": ["Cannonball"]},
    'cap32': {"display": "Amstrad - CPC/GX4000 (Caprice32)", "system": "CPC/GX4000", "manufacturer": "Amstrad", "license": "GPLv2", "extensions": "dsk|sna|zip|tap|cdt|voc|cpr|m3u", "databases": ["Amstrad - CPC", "Amstrad - GX4000"]},
    'cdi2015': {"display": "Philips CDi (CDi 2015)", "system": "CDi", "manufacturer": "Philips", "license": "GPLv2+", "extensions": "chd", "firmware": ["cdimono1.zip"], "databases": ["Philips - CD-i"]},
    'chailove': {"display": "ChaiLove", "system": "ChaiLove", "manufacturer": "N/A", "license": "MIT", "extensions": "chai|chailove", "databases": ["ChaiLove"]},
    'chimerasnes': {"display": "Nintendo - SNES / SFC (ChimeraSNES)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "Non-commercial", "extensions": "smc|fig|sfc|gd3|gd7|dx2|bsx|bs|swc|st", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'citra2018': {"display": "Nintendo - 3DS (Citra 2018)", "system": "3DS", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "3ds|3dsx|elf|axf|cci|cxi|app", "databases": ["Nintendo - Nintendo 3DS"]},
    'citra_canary': {"display": "Nintendo - 3DS (Citra Canary/Experimental)", "system": "3DS", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "3ds|3dsx|elf|axf|cci|cxi|app", "databases": ["Nintendo - Nintendo 3DS"]},
    'citra': {"display": "Nintendo - 3DS (Citra)", "system": "3DS", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "3ds|3dsx|elf|axf|cci|cxi|app", "databases": ["Nintendo - Nintendo 3DS"]},
    'clownmdemu': {"display": "Sega - MD/CD (ClownMDEmu)", "system": "Sega Genesis", "manufacturer": "Sega", "license": "AGPLv3", "extensions": "bin|md|gen|cue|iso|chd", "databases": ["Sega - Mega-CD - Sega CD", "Sega - Mega Drive - Genesis"]},
    'craft': {"display": "Minecraft (Craft)", "system": "Minecraft Game Clone", "manufacturer": "Microsoft", "license": "MIT", "databases": ["Minecraft"]},
    'crocods': {"display": "Amstrad - CPC (CrocoDS)", "system": "CPC", "manufacturer": "Amstrad", "license": "MIT", "extensions": "dsk|sna|kcr", "databases": ["Amstrad - CPC"]},
    'cruzes': {"display": "Cruzes", "system": "Cruzes", "manufacturer": "N/A", "license": "2-clause BSD", "extensions": "game"},
    'daphne': {"display": "Arcade (Daphne)", "system": "Arcade (various)", "manufacturer": "Various", "license": "GPLv2+", "extensions": "zip"},
    'desmume2015': {"display": "Nintendo - DS (DeSmuME 2015)", "system": "Nintendo DS", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "nds|ids|bin", "databases": ["Nintendo - Nintendo DS", "Nintendo - Nintendo DS (Download Play)"]},
    'desmume': {"display": "Nintendo - DS (DeSmuME)", "system": "Nintendo DS", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "nds|ids|bin", "databases": ["Nintendo - Nintendo DS", "Nintendo - Nintendo DS (Download Play)"]},
    'dice': {"display": "Arcade (DICE)", "system": "Arcade (various)", "manufacturer": "Various", "license": "GPLv3", "extensions": "zip|dmy|k1|a1|6c|c6|d2|s1|f4|a4|1da|da1|C4|4c|4d|d7|d4", "databases": ["DICE"]},
    'dinothawr': {"display": "Dinothawr", "system": "Dinothawr Game Engine", "manufacturer": "N/A", "license": "Non-commercial", "extensions": "game", "databases": ["Dinothawr"]},
    'directxbox': {"display": "Microsoft - Xbox (DirectXbox)", "system": "Xbox", "manufacturer": "Microsoft", "license": "GPLv2+", "extensions": "iso", "databases": ["Microsoft - Xbox"]},
    'dirksimple': {"display": "Laserdisc arcade game (DirkSimple)", "system": "Laserdisc arcade game", "manufacturer": "various", "license": "zlib", "extensions": "ogv|dirksimple"},
    'dolphin_launcher': {"display": "Nintendo - GameCube / Wii (Dolphin Launcher)", "system": "GameCube / Wii", "manufacturer": "Nintendo", "license": "MIT", "extensions": "elf|dol|gcm|iso|wbfs|ciso|gcz|wad", "databases": ["Nintendo - GameCube", "Nintendo - Wii", "Nintendo - Wii (Digital)"]},
    'dolphin': {"display": "Nintendo - GameCube / Wii (Dolphin)", "system": "GameCube / Wii", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "gcm|iso|wbfs|ciso|gcz|elf|dol|dff|tgc|wad|rvz|m3u|wia", "firmware": ["dolphin-emu/Sys/codehandler.bin"], "databases": ["Nintendo - GameCube", "Nintendo - Wii", "Nintendo - Wii (Digital)"]},
    'dosbox_core': {"display": "DOS (DOSBox-core)", "system": "DOS", "manufacturer": "Microsoft", "license": "GPLv2", "extensions": "exe|com|bat|conf|cue|iso|img|/", "databases": ["DOS"]},
    'dosbox': {"display": "DOS (DOSBox)", "system": "DOS", "manufacturer": "Microsoft", "license": "GPLv2", "extensions": "exe|com|bat|conf", "databases": ["DOS"]},
    'dosbox_pure': {"display": "DOS (DOSBox-Pure)", "system": "DOS", "manufacturer": "Microsoft", "license": "GPLv2", "extensions": "zip|dosz|exe|com|bat|iso|chd|cue|ins|img|ima|vhd|jrc|tc|m3u|m3u8|conf|/", "databases": ["DOS"]},
    'dosbox_svn_ce': {"display": "DOS (DOSBox-SVN CE)", "system": "DOS", "manufacturer": "Microsoft", "license": "GPLv2", "extensions": "exe|com|bat|conf|cue|iso", "databases": ["DOS"]},
    'dosbox_svn': {"display": "DOS (DOSBox-SVN)", "system": "DOS", "manufacturer": "Microsoft", "license": "GPLv2", "extensions": "exe|com|bat|conf|cue|iso|img|/", "databases": ["DOS"]},
    'doukutsu_rs': {"display": "Cave Story (drs)", "system": "Cave Story Game Engine", "license": "MIT", "extensions": "exe|dll|so", "databases": ["Cave Story"]},
    'duckstation': {"display": "Sony - PlayStation (DuckStation)", "system": "PlayStation", "manufacturer": "Sony", "license": "Non-commercial", "extensions": "exe|psexe|cue|bin|img|iso|chd|pbp|ecm|mds|psf|m3u", "firmware": ["scph5500.bin", "scph5501.bin", "scph5502.bin"], "databases": ["Sony - PlayStation"]},
    'easyrpg': {"display": "RPG Maker 2000/2003 (EasyRPG)", "system": "RPG Maker 2000/2003 Game Engine", "license": "GPLv3", "extensions": "ldb|zip|lzh|easyrpg", "databases": ["RPG Maker"]},
    'ecwolf': {"display": "Wolfenstein 3D (ECWolf)", "system": "Wolfenstein 3D Game Engine", "manufacturer": "Id Software", "license": "BSD|LGPL", "extensions": "wl6|n3d|sod|sdm|wl1|pk3|exe", "firmware": ["ecwolf.pk3"], "databases": ["Wolfenstein 3D"]},
    'emuscv': {"display": "EPOCH/YENO Super Cassette Vision", "system": "Super Cassette Vision", "manufacturer": "EPOCH/YENO", "license": "GPLv3", "extensions": "cart|bin|rom|0|zip", "firmware": ["upd7801g.s01"], "databases": ["Epoch - Super Cassette Vision"]},
    'emux_chip8': {"display": "CHIP-8 (Emux CHIP-8)", "system": "CHIP-8", "manufacturer": "Joseph Weisbecker", "license": "GPLv2", "extensions": "ch8|bin|rom"},
    'emux_gb': {"display": "Nintendo - Game Boy / Color (Emux GB)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "gb|gbc|bin|rom", "firmware": ["dmg_boot.bin"], "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'emux_nes': {"display": "Nintendo - NES / Famicom (Emux NES)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "nes|bin|rom", "databases": ["Nintendo - Nintendo Entertainment System"]},
    'emux_sms': {"display": "Sega - Master System (Emux SMS)", "system": "Sega Master System", "manufacturer": "Sega", "license": "GPLv2", "extensions": "sms|bms|bin|rom", "firmware": ["bios.sms"], "databases": ["Sega - Master System - Mark III"]},
    'ep128emu_core': {"display": "Enterprise - 64/128 (ep128emu)", "system": "128", "manufacturer": "Enterprise", "license": "GPLv2", "extensions": "img|dsk|tap|dtf|com|trn|128|bas|cas|cdt|tzx|wav|tvcwav|.", "databases": ["Enterprise - 128", "Amstrad - CPC", "Sinclair - ZX Spectrum", "Videoton - TV-Computer"]},
    'eternal': {"display": "Eternal Computer", "system": "Eternal Computer", "manufacturer": "Eternal Software Initiative", "license": "MIT", "extensions": "capsule|bootimage", "databases": ["eternal"]},
    'fake08': {"display": "PICO-8 (FAKE-08)", "system": "PICO-8", "manufacturer": "Lexaloffle", "license": "MIT", "extensions": "p8|png", "databases": ["PICO-8"]},
    'fbalpha2012_cps1': {"display": "Arcade (FB Alpha 2012 CPS-1)", "system": "CP System I", "manufacturer": "Capcom", "license": "Non-commercial", "extensions": "zip"},
    'fbalpha2012_cps2': {"display": "Arcade (FB Alpha 2012 CPS-2)", "system": "CP System II", "manufacturer": "Capcom", "license": "Non-commercial", "extensions": "zip"},
    'fbalpha2012_cps3': {"display": "Arcade (FB Alpha 2012 CPS-3)", "system": "CP System III", "manufacturer": "Capcom", "license": "Non-commercial", "extensions": "zip"},
    'fbalpha2012': {"display": "Arcade (FB Alpha 2012)", "system": "Arcade (various)", "manufacturer": "Various", "license": "Non-commercial", "extensions": "iso|zip|7z"},
    'fbalpha2012_neogeo': {"display": "Arcade (FB Alpha 2012 Neo Geo)", "system": "Neo Geo", "manufacturer": "SNK", "license": "Non-commercial", "extensions": "zip"},
    'fbneo_cps12': {"display": "Arcade (FinalBurn Neo) (CPS-1 / CPS-2)", "system": "CP System I/II", "manufacturer": "Capcom", "license": "Non-commercial", "extensions": "zip|7z", "databases": ["FBNeo - Arcade Games"]},
    'fbneo': {"display": "Arcade (FinalBurn Neo)", "system": "Arcade (various)", "manufacturer": "Various", "license": "Non-commercial", "extensions": "zip|7z|cue|ccd", "databases": ["FBNeo - Arcade Games"]},
    'fbneo_neogeo': {"display": "Arcade (FinalBurn Neo) (Neo-Geo)", "system": "Neo Geo", "manufacturer": "SNK", "license": "Non-commercial", "extensions": "zip|7z|cue|ccd", "databases": ["FBNeo - Arcade Games"]},
    'fceumm': {"display": "Nintendo - NES / Famicom (FCEUmm)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "fds|nes|unif|unf", "databases": ["Nintendo - Nintendo Entertainment System", "Nintendo - Family Computer Disk System"]},
    'ffmpeg': {"display": "FFmpeg", "system": "FFmpeg", "license": "LGPLv2, GPLv2", "extensions": "mkv|avi|f4v|f4f|3gp|ogm|flv|mp4|mp3|flac|ogg|m4a|webm|3g2|mov|wmv|mpg|mpeg|vob|asf|divx|m2p|m2ts|ps|ts|mxf|wma|wav"},
    'fixgb': {"display": "Nintendo - Game Boy / Color (fixGB)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "MIT", "extensions": "gb|gbc|gbs", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'fixnes': {"display": "Nintendo - NES / Famicom (fixNES)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "MIT", "extensions": "nes|fds|qd|nsf", "databases": ["Nintendo - Nintendo Entertainment System", "Nintendo - Family Computer Disk System"]},
    'flycast_gles2': {"display": "Sega - Dreamcast/Naomi (Flycast GLES2)", "system": "Sega Dreamcast", "manufacturer": "Sega", "license": "GPLv2", "extensions": "chd|cdi|iso|elf|bin|cue|gdi|lst|zip|dat|7z|m3u", "databases": ["Sega - Dreamcast", "Sega - Naomi"]},
    'flycast': {"display": "Sega - Dreamcast/Naomi (Flycast)", "system": "Sega Dreamcast", "manufacturer": "Sega", "license": "GPLv2", "extensions": "chd|cdi|elf|bin|cue|gdi|lst|zip|dat|7z|m3u", "databases": ["Sega - Dreamcast", "Sega - Naomi", "Sega - Naomi 2", "Atomiswave"]},
    'fmsx': {"display": "Microsoft - MSX (fMSX)", "system": "MSX", "manufacturer": "Various", "license": "Non-commercial", "extensions": "rom|mx1|mx2|dsk|fdi|cas|m3u", "firmware": ["MSX.ROM", "MSX2.ROM", "MSX2EXT.ROM", "MSX2P.ROM", "MSX2PEXT.ROM"], "databases": ["Microsoft - MSX", "Microsoft - MSX2"]},
    'freechaf': {"display": "Fairchild - ChannelF (FreeChaF)", "system": "FreeChaF", "manufacturer": "Fairchild", "license": "GPLv3", "extensions": "bin|chf", "firmware": ["sl31253.bin", "sl31254.bin", "sl90025.bin"], "databases": ["Fairchild - Channel F"]},
    'freeintv': {"display": "Mattel - Intellivision (FreeIntv)", "system": "Intellivision", "manufacturer": "Mattel", "license": "GPLv3", "extensions": "int|bin|rom", "firmware": ["exec.bin", "grom.bin"], "databases": ["Mattel - Intellivision"]},
    'freej2me': {"display": "Mobile - J2ME (FreeJ2ME)", "system": "J2ME", "manufacturer": "Java", "license": "GPLv3", "extensions": "jar", "firmware": ["freej2me-lr.jar"], "databases": ["Mobile - J2ME"]},
    'frodo': {"display": "Commodore - C64 (Frodo)", "system": "C64", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|t64|x64|p00|lnx|lyx|zip", "databases": ["Commodore - 64"]},
    'fsuae': {"display": "Commodore - Amiga (FS-UAE)", "system": "Commodore Amiga", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "adf|ipf|fs-uae", "databases": ["Commodore - Amiga"]},
    'fuse': {"display": "Sinclair - ZX Spectrum (Fuse)", "system": "ZX Spectrum (various)", "manufacturer": "Sinclair|Amstrad", "license": "GPLv3", "extensions": "tzx|tap|z80|rzx|scl|trd|dsk|dck|sna|szx|zip", "databases": ["Sinclair - ZX Spectrum +3", "Sinclair - ZX Spectrum"]},
    'galaksija': {"display": "Elektronika Inženjering - Galaksija (Galaksija)", "manufacturer": "Zavod za udžbenike i nastavna sredstva with Elektronika Inženjering", "license": "Public Domain", "extensions": "gal"},
    'gam4980': {"display": "GAM4980", "system": "Longman 4980", "manufacturer": "BBK Electronics", "license": "GPLv3+", "extensions": "gam", "databases": ["gam4980"]},
    'gambatte': {"display": "Nintendo - Game Boy / Color (Gambatte)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "gb|gbc|dmg", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'gearboy': {"display": "Nintendo - Game Boy / Color (Gearboy)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "gb|dmg|gbc|cgb|sgb", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'gearcoleco': {"display": "Coleco - ColecoVision (Gearcoleco)", "system": "ColecoVision", "manufacturer": "Coleco", "license": "GPLv3", "extensions": "col|cv|bin|rom", "firmware": ["colecovision.rom"], "databases": ["Coleco - ColecoVision"]},
    'geargrafx': {"display": "NEC - PC Engine / SuperGrafx / CD (Geargrafx)", "system": "PC Engine/SuperGrafx", "manufacturer": "NEC", "license": "GPLv3", "extensions": "pce|sgx|cue|chd", "databases": ["NEC - PC Engine SuperGrafx", "NEC - PC Engine - TurboGrafx 16", "NEC - PC Engine CD - TurboGrafx-CD"]},
    'gearlynx': {"display": "Atari - Lynx (GearLynx)", "system": "Lynx", "manufacturer": "Atari", "license": "GPLv3", "extensions": "lnx|lyx|o", "firmware": ["lynxboot.img"], "databases": ["Atari - Lynx"]},
    'gearsystem': {"display": "Sega - MS/GG/SG-1000 (Gearsystem)", "system": "Sega 8-bit (MS/GG/SG-1000)", "manufacturer": "Sega", "license": "GPLv3", "extensions": "sms|gg|sg|mv|bin|rom", "databases": ["Sega - Game Gear", "Sega - Master System - Mark III", "Sega - SG-1000"]},
    'genesis_plus_gx': {"display": "Sega - MS/GG/MD/CD (Genesis Plus GX)", "system": "Sega 8/16-bit (Various)", "manufacturer": "Sega", "license": "Non-commercial", "extensions": "mdx|md|smd|gen|bin|cue|iso|sms|bms|gg|sg|68k|sgd|chd|m3u", "databases": ["Sega - Game Gear", "Sega - Master System - Mark III", "Sega - Mega-CD - Sega CD", "Sega - Mega Drive - Genesis", "Sega - PICO", "Sega - SG-1000"]},
    'genesis_plus_gx_wide': {"display": "Sega - MS/GG/MD/CD (Genesis Plus GX Wide)", "system": "Sega 8/16-bit (Various)", "manufacturer": "Sega", "license": "Non-commercial", "extensions": "mdx|md|smd|gen|bin|cue|iso|sms|bms|gg|sg|68k|sgd|chd|m3u", "databases": ["Sega - Game Gear", "Sega - Master System - Mark III", "Sega - Mega-CD - Sega CD", "Sega - Mega Drive - Genesis", "Sega - PICO", "Sega - SG-1000"]},
    'geolith': {"display": "SNK - Neo Geo AES/MVS/CD (Geolith)", "system": "Neo Geo", "manufacturer": "SNK", "license": "BSD-3-Clause, MIT", "extensions": "neo|cue|chd", "firmware": ["aes.zip", "neogeo.zip", "neocd.zip", "neocdz.zip"], "databases": ["SNK - Neo Geo"]},
    'gme': {"display": "Game Music Emu", "system": "Music", "manufacturer": "Various", "license": "GPLv3", "extensions": "ay|gbs|gym|hes|kss|nsf|nsfe|sap|spc|vgm|vgz|zip"},
    'gong': {"display": "Gong", "system": "Pong Game Clone", "manufacturer": "N/A", "license": "GPL v3"},
    'gpsp': {"display": "Nintendo - Game Boy Advance (gpSP)", "system": "Game Boy Advance", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "gba|bin", "firmware": ["gba_bios.bin"], "databases": ["Nintendo - Game Boy Advance"]},
    'gw': {"display": "Handheld Electronic (GW)", "system": "Handheld Electronic", "manufacturer": "Various", "license": "zlib", "extensions": "mgw", "databases": ["Handheld Electronic Game"]},
    'handy': {"display": "Atari - Lynx (Handy)", "system": "Lynx", "manufacturer": "Atari", "license": "Zlib", "extensions": "lnx|lyx|o", "databases": ["Atari - Lynx"]},
    'hatari': {"display": "Atari - ST/STE/TT/Falcon (Hatari)", "system": "Atari ST/STE/TT/Falcon", "manufacturer": "Atari", "license": "GPLv2", "extensions": "st|msa|zip|stx|dim|ipf|vhd|gem|ide|m3u", "firmware": ["tos.img"], "databases": ["Atari - ST"]},
    'hbmame': {"display": "Arcade (HBMAME)", "system": "Arcade (various)", "manufacturer": "Various", "license": "GPLv2+", "extensions": "zip|chd|7z|cmd", "databases": ["HBMAME"]},
    'higan_sfc_balanced': {"display": "Nintendo - SNES / Famicom (nSide Balanced)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|gb|gbc|bml|rom", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'higan_sfc': {"display": "Nintendo - SNES / Famicom (higan Accuracy)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|gb|gbc|bml|rom", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'holani': {"display": "Atari - Lynx (Holani)", "system": "Lynx", "manufacturer": "Atari", "license": "GPLv3", "extensions": "lnx|o", "databases": ["Atari - Lynx"]},
    'imageviewer': {"display": "Imageviewer", "extensions": "jpg|jpeg|png|bmp|psd|tga|gif|hdr|pic|ppm|pgm"},
    'irogb': {"display": "Nintendo - Game Boy / Color (IroGB)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "gb|gbc|dmg|cgb", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'ishiiruka': {"display": "Nintendo - GameCube / Wii (Ishiiruka)", "system": "GameCube / Wii", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "gcm|iso|wbfs|ciso|gcz|elf|dol|dff|tgc|wad", "databases": ["Nintendo - GameCube", "Nintendo - Wii", "Nintendo - Wii (Digital)"]},
    'jaxe': {"display": "CHIP-8/S-CHIP/XO-CHIP (JAXE)", "system": "CHIP-8", "manufacturer": "RCA", "license": "MIT", "extensions": "ch8|sc8|xo8", "databases": ["CHIP-8"]},
    'jollycv': {"display": "ColecoVision/CreatiVision/My Vision (JollyCV)", "system": "ColecoVision/CreatiVision/My Vision", "manufacturer": "Coleco|VTech|Nichibutsu", "license": "BSD-3-Clause, MIT", "extensions": "col|rom|myv|bin", "databases": ["Coleco - ColecoVision"]},
    'jumpnbump': {"display": "Jump 'n Bump", "manufacturer": "Brainchild Design", "license": "GPLv2", "extensions": "dat", "databases": ["Jump 'n Bump"]},
    'kronos': {"display": "Sega - Saturn/ST-V (Kronos)", "system": "Saturn", "manufacturer": "Sega", "license": "GPLv2", "extensions": "ccd|chd|cue|iso|mds|zip|m3u", "firmware": ["kronos/saturn_bios.bin", "kronos/stvbios.zip"], "databases": ["Sega - Saturn", "Sega - ST-V"]},
    'lowresnx': {"display": "LowRes NX", "system": "LowRes NX", "manufacturer": "inutilis", "license": "zlib", "extensions": "nx", "databases": ["LowRes NX"]},
    'lutro': {"display": "Lua Engine (Lutro)", "system": "Lutro", "license": "MIT", "extensions": "lutro|love|lua", "databases": ["Lutro"]},
    'm2000': {"display": "Philips - P2000T (M2000)", "system": "P2000T", "manufacturer": "Philips", "license": "GPLv3", "extensions": "cas", "databases": ["Philips - P2000T"]},
    'mame2000': {"display": "Arcade (MAME 2000)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip|7z", "databases": ["MAME 2000"]},
    'mame2003': {"display": "Arcade (MAME 2003)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip", "databases": ["MAME 2003"]},
    'mame2003_midway': {"display": "Arcade (MAME 2003 Midway)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip", "databases": ["MAME 2003 (Midway)"]},
    'mame2003_plus': {"display": "Arcade (MAME 2003-Plus)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME Noncommercial", "extensions": "zip", "databases": ["MAME 2003-Plus"]},
    'mame2009': {"display": "Arcade (MAME 2009)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip|7z", "databases": ["MAME 2009"]},
    'mame2010': {"display": "Arcade (MAME 2010)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip|7z", "databases": ["MAME 2010"]},
    'mame2015': {"display": "Arcade (MAME 2015)", "system": "Arcade (various)", "manufacturer": "Various", "license": "MAME", "extensions": "cmd|zip|7z", "databases": ["MAME 2015"]},
    'mame2016': {"display": "Arcade (MAME 2016)", "system": "Arcade (various)", "manufacturer": "Various", "license": "GPLv2+", "extensions": "cmd|zip|7z", "databases": ["MAME 2016"]},
    'mame': {"display": "Arcade (MAME)", "system": "Arcade (various)", "manufacturer": "Various", "license": "GPLv2+", "extensions": "cmd|zip|7z", "databases": ["MAME"]},
    'mamearcade': {"display": "Arcade (MAME/Arcade)", "system": "Arcade (various)", "manufacturer": "Various", "license": "GPLv2+", "extensions": "cmd|zip|7z", "databases": ["MAME"]},
    'mamemess': {"display": "Multi (MAME/MESS)", "system": "Multi (various)", "manufacturer": "Various", "license": "GPLv2+", "extensions": "cmd|zip|7z", "databases": ["MAME"]},
    'mcsoftserve': {"display": "McSoftServe", "system": "C713", "manufacturer": "Taylor", "license": "MIT"},
    'mednafen_gba': {"display": "Nintendo - Game Boy Advance (Beetle GBA)", "system": "Game Boy Advance", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "gba|agb|bin", "databases": ["Nintendo - Game Boy Advance"]},
    'mednafen_lynx': {"display": "Atari - Lynx (Beetle Lynx)", "system": "Lynx", "manufacturer": "Atari", "license": "Zlib|GPLv2", "extensions": "lnx|lyx|bll|o", "firmware": ["lynxboot.img"], "databases": ["Atari - Lynx"]},
    'mednafen_ngp': {"display": "SNK - Neo Geo Pocket / Color (Beetle NeoPop)", "system": "Neo Geo Pocket (Color)", "manufacturer": "SNK", "license": "GPLv2", "extensions": "ngp|ngc|ngpc|npc", "databases": ["SNK - Neo Geo Pocket", "SNK - Neo Geo Pocket Color"]},
    'mednafen_pce_fast': {"display": "NEC - PC Engine / CD (Beetle PCE FAST)", "system": "PC Engine/PCE-CD", "manufacturer": "NEC", "license": "GPLv2", "extensions": "pce|cue|ccd|chd|toc|m3u", "databases": ["NEC - PC Engine - TurboGrafx 16", "NEC - PC Engine CD - TurboGrafx-CD"]},
    'mednafen_pce': {"display": "NEC - PC Engine / SuperGrafx / CD (Beetle PCE)", "system": "PC Engine/SuperGrafx/CD", "manufacturer": "NEC", "license": "GPLv2", "extensions": "pce|sgx|cue|ccd|chd|toc|m3u", "databases": ["NEC - PC Engine SuperGrafx", "NEC - PC Engine - TurboGrafx 16", "NEC - PC Engine CD - TurboGrafx-CD"]},
    'mednafen_pcfx': {"display": "NEC - PC-FX (Beetle PC-FX)", "system": "PC-FX", "manufacturer": "NEC", "license": "GPLv2", "extensions": "cue|ccd|toc|chd", "firmware": ["pcfx.rom"], "databases": ["NEC - PC-FX"]},
    'mednafen_psx_hw': {"display": "Sony - PlayStation (Beetle PSX HW)", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "cue|toc|m3u|ccd|exe|pbp|chd|bin", "firmware": ["scph5500.bin", "scph5501.bin", "scph5502.bin"], "databases": ["Sony - PlayStation"]},
    'mednafen_psx': {"display": "Sony - PlayStation (Beetle PSX)", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "cue|toc|m3u|ccd|exe|pbp|chd|bin", "firmware": ["scph5500.bin", "scph5501.bin", "scph5502.bin"], "databases": ["Sony - PlayStation"]},
    'mednafen_saturn': {"display": "Sega - Saturn (Beetle Saturn)", "system": "Saturn", "manufacturer": "Sega", "license": "GPLv2", "extensions": "ccd|chd|cue|toc|m3u|zip", "firmware": ["sega_101.bin", "mpr-17933.bin"], "databases": ["Sega - Saturn"]},
    'mednafen_snes': {"display": "Nintendo - SNES / SFC (Beetle bsnes)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "smc|fig|bs|st|sfc", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo"]},
    'mednafen_supafaust': {"display": "Nintendo - SNES / SFC (Beetle Supafaust)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv2+", "extensions": "smc|fig|sfc|gd3|gd7|dx2|bsx|swc", "databases": ["Nintendo - Super Nintendo Entertainment System"]},
    'mednafen_supergrafx': {"display": "NEC - PC Engine SuperGrafx (Beetle SuperGrafx)", "system": "PC Engine SuperGrafx", "manufacturer": "NEC", "license": "GPLv2", "extensions": "pce|sgx|cue|ccd|chd", "databases": ["NEC - PC Engine SuperGrafx", "NEC - PC Engine - TurboGrafx 16", "NEC - PC Engine CD - TurboGrafx-CD"]},
    'mednafen_vb': {"display": "Nintendo - Virtual Boy (Beetle VB)", "system": "Virtual Boy", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "vb|vboy|bin", "databases": ["Nintendo - Virtual Boy"]},
    'mednafen_wswan': {"display": "Bandai - WonderSwan/Color (Beetle Wonderswan)", "system": "WonderSwan/Color", "manufacturer": "Bandai", "license": "GPLv2", "extensions": "ws|wsc|pc2|pcv2", "databases": ["Bandai - WonderSwan", "Bandai - WonderSwan Color"]},
    'melonds': {"display": "Nintendo - DS (melonDS)", "system": "Nintendo DS", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "nds|ids|dsi", "databases": ["Nintendo - Nintendo DS", "Nintendo - Nintendo DS (Download Play)", "Nintendo - Nintendo DSi", "Nintendo - Nintendo DSi Decrypted", "Nintendo - Nintendo DSi (Digital)"]},
    'melondsds': {"display": "Nintendo - DS (melonDS DS)", "system": "Nintendo DS", "manufacturer": "Nintendo", "license": "GPLv3+", "extensions": "nds|ids|dsi", "databases": ["Nintendo - Nintendo DS", "Nintendo - Nintendo DS (Download Play)", "Nintendo - Nintendo DSi", "Nintendo - Nintendo DSi Decrypted", "Nintendo - Nintendo DSi (Digital)"]},
    'mesen-s': {"display": "Nintendo - SNES / SFC / Game Boy / Color (Mesen-S)", "system": "Super Nintendo Entertainment System / Game Boy / Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "sfc|smc|fig|swc|bs|gb|gbc", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Satellaview", "Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'mesen': {"display": "Nintendo - NES / Famicom (Mesen)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "nes|fds|unf|unif", "databases": ["Nintendo - Nintendo Entertainment System", "Nintendo - Family Computer Disk System"]},
    'mess2015': {"display": "Multi (MESS 2015)", "system": "Multi (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip|chd|7z"},
    'meteor': {"display": "Nintendo - Game Boy Advance (Meteor)", "system": "Game Boy Advance", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "gba", "databases": ["Nintendo - Game Boy Advance"]},
    'mgba': {"display": "Nintendo - Game Boy Advance (mGBA)", "system": "Game Boy/Game Boy Color/Game Boy Advance", "manufacturer": "Nintendo", "license": "MPLv2.0", "extensions": "gb|gbc|gba", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color", "Nintendo - Game Boy Advance"]},
    'minivmac': {"display": "Mac II (minivmac)", "system": "Mac68k", "manufacturer": "Apple", "license": "GPLv2", "extensions": "dsk|img|zip|hvf|cmd", "firmware": ["MacII.ROM"]},
    'mkxp-z': {"display": "RPG Maker XP/VX/VX Ace (mkxp-z)", "system": "RPG Maker XP/VX/VX Ace Game Engine", "license": "GPLv2", "extensions": "ini|json|rxproj|rvproj|rvproj2|mkxpz|zip|7z", "databases": ["RPG Maker"]},
    'mojozork': {"display": "Infocom Z-Machine (MojoZork)", "system": "Z-Machine", "manufacturer": "Infocom", "license": "zlib", "extensions": "dat|z1|z3", "databases": ["Infocom - Z-Machine"]},
    'moonlight': {"display": "Moonlight", "system": "Moonlight", "manufacturer": "NVIDIA", "license": "GPLv3"},
    'mpv': {"display": "MPV", "system": "MPV", "license": "LGPLv2, GPLv2", "extensions": "mkv|avi|f4v|f4f|3gp|ogm|flv|mp4|mp3|flac|ogg|m4a|webm|3g2|mov|wmv|mpg|mpeg|vob|asf|divx|m2p|m2ts|ps|ts|mxf|wma|wav"},
    'mrboom': {"display": "Mr.Boom (Bomberman)", "system": "Mr.Boom", "license": "MIT", "extensions": "desktop", "databases": ["MrBoom"]},
    'mu': {"display": "Palm OS (Mu)", "system": "Palm OS", "manufacturer": "Palm", "license": "CC BY-NC 3.0 US (Non-commercial)", "extensions": "prc|pqa|img|pdb|zip", "firmware": ["palmos41-en-m515.rom"]},
    'mupen64plus_next_develop': {"display": "Nintendo - Nintendo 64 (Mupen64Plus-Next Develop)", "system": "Nintendo 64", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "n64|v64|z64|ndd|bin|u1", "databases": ["Nintendo - Nintendo 64"]},
    'mupen64plus_next_gles2': {"display": "Nintendo - Nintendo 64 (Mupen64Plus-Next GLES2)", "system": "Nintendo 64", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "n64|v64|z64|ndd|bin|u1", "databases": ["Nintendo - Nintendo 64"]},
    'mupen64plus_next_gles3': {"display": "Nintendo - Nintendo 64 (Mupen64Plus-Next GLES3)", "system": "Nintendo 64", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "n64|v64|z64|ndd|bin|u1", "databases": ["Nintendo - Nintendo 64"]},
    'mupen64plus_next': {"display": "Nintendo - Nintendo 64 (Mupen64Plus-Next)", "system": "Nintendo 64", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "n64|v64|z64|ndd|bin|u1", "databases": ["Nintendo - Nintendo 64"]},
    'native32emu': {"display": "Native32 (Native32Emu)", "system": "Native32", "manufacturer": "Sunplus", "license": "BSD-3-Clause", "extensions": "smf|sgm|ssl|zip", "databases": ["Native32"]},
    'nekop2': {"display": "NEC - PC-98 (Neko Project II)", "system": "PC-98", "manufacturer": "NEC", "license": "MIT", "extensions": "d98|zip|98d|fdi|fdd|2hd|tfd|d88|88d|hdm|xdf|dup|cmd|hdi|thd|nhd|hdd", "databases": ["NEC - PC-98"]},
    'neocd': {"display": "SNK - Neo Geo CD (NeoCD)", "system": "SNK Neo Geo CD", "manufacturer": "SNK", "license": "LGPLv3", "extensions": "cue|chd", "databases": ["SNK - Neo Geo CD"]},
    'nes': {"display": "Nintendo - NES / Famicom (nes)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "ISC", "extensions": "nes", "databases": ["Nintendo - Nintendo Entertainment System"]},
    'nestopia': {"display": "Nintendo - NES / Famicom (Nestopia)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "nes|fds|unf|unif", "databases": ["Nintendo - Nintendo Entertainment System", "Nintendo - Family Computer Disk System"]},
    'noods': {"display": "Nintendo - DS (NooDS)", "system": "Nintendo DS", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "nds|gba", "databases": ["Nintendo - Nintendo DS", "Nintendo - Nintendo DS (Download Play)"]},
    'np2kai': {"display": "NEC - PC-98 (Neko Project II Kai)", "system": "PC-98", "manufacturer": "NEC", "license": "MIT", "extensions": "d98|zip|98d|fdi|fdd|2hd|tfd|d88|88d|hdm|xdf|dup|cmd|hdi|thd|nhd|hdd|hdn", "databases": ["NEC - PC-98"]},
    'nuance': {"display": "VM Labs - NUON (Nuance)", "system": "NUON", "manufacturer": "VM Labs", "license": "Non-commercial", "extensions": "run|cof|nuon|cd|iso|img", "firmware": ["nuance/bios.cof", "nuance/minibios.cof", "nuance/minibiosX.cof"], "databases": ["VM Labs - NUON"]},
    'numero': {"display": "Texas Instruments TI-83 (Numero)", "system": "TI83", "manufacturer": "Texas Instruments", "license": "GPLv2", "extensions": "8xp|8xk|8xg"},
    'nxengine': {"display": "Cave Story (NXEngine)", "system": "Cave Story Game Engine", "license": "GPLv3", "extensions": "exe", "databases": ["Cave Story"]},
    'o2em': {"display": "Magnavox - Odyssey2 / Philips Videopac+ (O2EM)", "system": "Magnavox Odyssey2 / Philips Videopac+", "manufacturer": "Magnavox|Philips", "license": "Artistic License", "extensions": "bin", "firmware": ["o2rom.bin", "c52.bin", "g7400.bin", "jopac.bin"], "databases": ["Magnavox - Odyssey2", "Philips - Videopac+"]},
    'oberon': {"display": "Oberon RISC Emulator", "system": "Oberon RISC machine", "license": "ISC", "extensions": "dsk"},
    'onscripter': {"display": "ONScripter", "system": "ONScripter", "manufacturer": "ONScripter", "license": "GPLv3+", "extensions": "txt|dat|___|ons|/", "databases": ["ONScripter"]},
    'onsyuri': {"display": "ONScripter Yuri", "system": "ONScripter Yuri", "manufacturer": "ONScripter", "license": "GPLv2+", "extensions": "txt|dat|___|nt2|nt3|ons|/", "databases": ["ONScripter"]},
    'open-source-notices': {},
    'openlara': {"display": "Tomb Raider (OpenLara)", "system": "Classic Tomb Raider engine", "license": "2-clause BSD", "extensions": "phd|psx|tr2", "databases": ["Tomb Raider"]},
    'opentyrian': {"display": "Tyrian (OpenTyrian)", "system": "Tyrian Game Engine", "license": "GPLv3", "databases": ["Tyrian"]},
    'opera': {"display": "The 3DO Company - 3DO (Opera)", "system": "3DO", "manufacturer": "Panasonic|GoldStar|Sanyo", "license": "LGPL/Non-commercial", "extensions": "iso|bin|chd|cue", "databases": ["The 3DO Company - 3DO"]},
    'panda3ds': {"display": "Nintendo - 3DS (Panda3DS)", "system": "3DS", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "3ds|3dsx|elf|axf|cci|cxi|app", "databases": ["Nintendo - Nintendo 3DS"]},
    'parallel_n64_debug': {"display": "Nintendo - Nintendo 64 (ParaLLEl) (Debug)", "system": "Nintendo 64", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "n64|v64|z64|bin|u1|ndd", "databases": ["Nintendo - Nintendo 64", "Nintendo - Nintendo 64DD"]},
    'parallel_n64': {"display": "Nintendo - Nintendo 64 (ParaLLEl N64)", "system": "Nintendo 64", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "n64|v64|z64|bin|u1|ndd", "databases": ["Nintendo - Nintendo 64", "Nintendo - Nintendo 64DD"]},
    'pascal_pong': {"display": "PascalPong", "license": "2-clause BSD", "extensions": "game"},
    'pcem': {"display": "PC (PCem)", "system": "PC", "manufacturer": "IBM", "license": "GPLv2", "extensions": "exe|com|bat|conf"},
    'pcsx1': {"display": "Sony - PlayStation (PCSX1)", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "bin|cue|img|mdf|pbp|toc|cbn|m3u", "databases": ["Sony - PlayStation"]},
    'pcsx2': {"display": "Sony - PlayStation 2 (LRPS2)", "system": "Sony PlayStation 2", "manufacturer": "Sony", "license": "GPL", "extensions": "elf|iso|ciso|cue|bin|gz|chd|cso|zso|mdf|nrg|dump|img|m3u", "firmware": ["pcsx2/bios", "pcsx2/resources/GameIndex.yaml"], "databases": ["Sony - PlayStation 2"]},
    'pcsx_rearmed_interpreter': {"display": "Sony - PlayStation (PCSX ReARMed) [Interpreter]", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "bin|cue|img|mdf|pbp|cbn|toc|chd", "databases": ["Sony - PlayStation"]},
    'pcsx_rearmed': {"display": "Sony - PlayStation (PCSX ReARMed)", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "bin|cue|img|mdf|pbp|toc|cbn|m3u|ccd|chd|iso|exe", "databases": ["Sony - PlayStation"]},
    'pcsx_rearmed_neon': {"display": "Sony - PlayStation (PCSX ReARMed) [NEON]", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "bin|cue|img|mdf|pbp|toc|cbn|m3u|chd", "databases": ["Sony - PlayStation"]},
    'pd777': {"display": "Epoch - Cassette Vision (PD777)", "system": "Epoch Cassette Vision", "manufacturer": "Epoch", "license": "MIT", "extensions": "zip|bin777|ptn777", "databases": ["Epoch - Cassette Vision"]},
    'picodrive': {"display": "Sega - MS/GG/MD/CD/32X (PicoDrive)", "system": "Sega 8/16-bit + 32X (Various)", "manufacturer": "Sega", "license": "MAME", "extensions": "bin|gen|smd|md|32x|cue|iso|chd|sms|gg|sg|sc|m3u|68k|sgd|pco", "databases": ["Sega - Master System - Mark III", "Sega - Game Gear", "Sega - Mega-CD - Sega CD", "Sega - Mega Drive - Genesis", "Sega - PICO", "Sega - 32X"]},
    'piece': {"display": "Aquaplus - P/ECE (piece-emu)", "system": "P/ECE", "manufacturer": "Aquaplus", "license": "MIT", "extensions": "pfi"},
    'play': {"display": "Sony - PlayStation 2 (Play!)", "system": "Sony PlayStation 2", "manufacturer": "Sony", "license": "MIT", "extensions": "chd|cso|cue|elf|iso|isz", "databases": ["Sony - PlayStation 2"]},
    'pocketcdg': {"display": "PocketCDG", "system": "Music", "license": "MIT", "extensions": "cdg"},
    'pokemini': {"display": "Nintendo - Pokemon Mini (PokeMini)", "system": "Pokemon Mini", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "min", "databases": ["Nintendo - Pokemon Mini"]},
    'potator': {"display": "Watara - Supervision (Potator)", "system": "Supervision", "manufacturer": "Watara", "license": "Public Domain", "extensions": "bin|sv", "databases": ["Watara - Supervision"]},
    'ppsspp': {"display": "Sony - PlayStation Portable (PPSSPP)", "system": "PSP", "manufacturer": "Sony", "license": "GPLv2", "extensions": "elf|iso|cso|prx|pbp|chd", "firmware": ["PPSSPP/ppge_atlas.zim"], "databases": ["Sony - PlayStation Portable"]},
    'prboom': {"display": "Doom (PrBoom)", "system": "DOOM Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "wad|iwad|pwad|pk3", "databases": ["DOOM"]},
    'prosystem': {"display": "Atari - 7800 (ProSystem)", "system": "Atari 7800", "manufacturer": "Atari", "license": "GPLv2", "extensions": "a78|bin|cdf", "databases": ["Atari - 7800"]},
    'puae2021': {"display": "Commodore - Amiga (PUAE 2021)", "system": "Amiga", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "adf|adz|dms|fdi|ipf|hdf|hdz|lha|slave|info|cue|ccd|nrg|mds|iso|chd|uae|m3u|zip|7z|rp9|/", "firmware": ["kick34005.A500", "kick40068.A1200", "kick40060.CD32", "kick40060.CD32.ext"], "databases": ["Commodore - Amiga", "Commodore - CD32", "Commodore - CDTV"]},
    'puae': {"display": "Commodore - Amiga (PUAE)", "system": "Amiga", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "adf|adz|dms|fdi|ipf|hdf|hdz|lha|slave|info|cue|ccd|nrg|mds|iso|chd|uae|m3u|zip|7z|rp9|/", "firmware": ["kick34005.A500", "kick40068.A1200", "kick40060.CD32", "kick40060.CD32.ext"], "databases": ["Commodore - Amiga", "Commodore - CD32", "Commodore - CDTV"]},
    'puzzlescript': {"display": "PuzzleScript (pzretro)", "system": "PuzzleScript", "license": "MIT", "extensions": "pz|pzp", "databases": ["PuzzleScript"]},
    'px68k': {"display": "Sharp - X68000 (PX68k)", "system": "Sharp X68000", "manufacturer": "Sharp", "license": "Custom Non-Commercial", "extensions": "dim|img|d88|88d|hdm|dup|2hd|xdf|hdf|cmd|m3u", "firmware": ["keropi/iplrom.dat", "keropi/cgrom.dat"], "databases": ["Sharp - X68000"]},
    'qemu': {"display": "QEMU", "license": "GPLv2", "extensions": "qemu_cmd_line|iso|img|qcow|qcow2"},
    'quasi88': {"display": "NEC - PC-8000 / PC-8800 series (QUASI88)", "system": "PC-8000 / PC-8800 series", "manufacturer": "NEC", "license": "BSD 3-Clause and MAME non-commercial", "extensions": "d88|u88|m3u", "firmware": ["quasi88/n88.rom", "quasi88/n88_0.rom"], "databases": ["NEC - PC-8001 - PC-8801"]},
    'quicknes': {"display": "Nintendo - NES / Famicom (QuickNES)", "system": "Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "LGPLv2.1+", "extensions": "nes", "databases": ["Nintendo - Nintendo Entertainment System"]},
    'race': {"display": "SNK - Neo Geo Pocket / Color (RACE)", "system": "Neo Geo Pocket (Color)", "manufacturer": "SNK", "license": "GPLv2", "extensions": "ngp|ngc|ngpc|npc", "databases": ["SNK - Neo Geo Pocket", "SNK - Neo Geo Pocket Color"]},
    'radio': {"display": "Internet Radio (Radio)", "system": "Internet Radio Player", "license": "MIT", "extensions": "m3u|txt"},
    'redbook': {"display": "Redbook Audio Player", "system": "Redbook", "license": "Apache 2.0", "extensions": "cue|bin"},
    'reminiscence': {"display": "Flashback (REminiscence)", "system": "Flashback Game Engine", "license": "GPLv3", "extensions": "map|aba|seq|lev", "databases": ["Flashback"]},
    'remotejoy': {"display": "PSP RemotePlay (RemoteJoy)", "license": "GPLv2"},
    'retro8': {"display": "PICO-8 (Retro8)", "system": "PICO-8", "manufacturer": "Lexaloffle", "license": "GPLv3", "extensions": "p8|png", "databases": ["PICO-8"]},
    'retrodream': {"display": "Sega - Dreamcast (RetroDream)", "system": "Sega Dreamcast", "manufacturer": "Sega", "license": "GPLv3", "extensions": "gdi|chd|cdi", "firmware": ["dc/boot.bin", "dc/flash.bin"], "databases": ["Sega - Dreamcast"]},
    'romcleaner': {"display": "ROM Cleaner", "manufacturer": "Various", "license": "MIT", "extensions": "sfc|smc|st|swc|bs|cgb|dmg|gb|gbc|sgb|a52|nes|3ds|3dsx|cart|rom|sms|bms|int|col|cv|md|mdx|smd|gen|gg|sg|gba|nds|lnx|lyx|pce|sgx|ws|wsc|vb|vboy|n64|z64|v64|vec"},
    'rustation': {"display": "Sony - PlayStation (Rustation)", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv2", "extensions": "cue|toc|m3u|ccd|exe", "databases": ["Sony - PlayStation"]},
    'rvvm': {"display": "RVVM", "system": "RVVM", "manufacturer": "RVVM", "license": "GPLv3+", "extensions": "rvvm", "databases": ["RVVM"]},
    'same_cdi': {"display": "Philips - CDi (SAME CDi)", "system": "CD-i", "manufacturer": "Philips", "license": "GPLv2+", "extensions": "chd|iso|cue", "firmware": ["same_cdi/bios/cdimono1.zip"], "databases": ["MAME", "Philips - CD-i"]},
    'sameboy': {"display": "Nintendo - Game Boy / Color (SameBoy)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "Expat", "extensions": "gb|gbc", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'sameduck': {"display": "Mega Duck / Cougar Boy (SameDuck)", "system": "Mega Duck", "manufacturer": "Welback Holdings", "license": "MIT", "extensions": "bin|duck"},
    'scummvm': {"display": "ScummVM", "system": "Game engine", "manufacturer": "Various", "license": "GPLv3", "extensions": "scummvm", "databases": ["ScummVM"]},
    'sdlpal': {"display": "SDLPAL", "system": "SDLPAL", "manufacturer": "N/A", "license": "GPLv3", "extensions": "cfg"},
    'simcp': {"display": "SAM Coupe (SimCoupe)", "system": "SAM coupe", "manufacturer": "Miles Gordon Technology", "license": "GPLv2", "extensions": "dsk|mgt|sbt|sad", "databases": ["SAM coupe"]},
    'skyemu': {"display": "Nintendo - Game Boy/GBA/NDS (SkyEmu)", "manufacturer": "Nintendo", "license": "MIT", "extensions": "gb|gbx|gba|nds", "databases": ["Nintendo - Nintendo DS", "Nintendo - Game Boy", "Nintendo - Game Boy Advance"]},
    'smsplus': {"display": "Sega - MS/GG (SMS Plus GX)", "system": "Sega 8-bit", "manufacturer": "Sega", "license": "GPLv2", "extensions": "sms|bin|rom|col|gg|sg", "databases": ["Sega - Game Gear", "Sega - Master System - Mark III"]},
    'snes9x2002': {"display": "Nintendo - SNES / SFC (Snes9x 2002)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "Non-commercial", "extensions": "smc|fig|sfc|gd3|gd7|dx2|bsx|swc", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'snes9x2005': {"display": "Nintendo - SNES / SFC (Snes9x 2005)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "Non-commercial", "extensions": "smc|fig|sfc|gd3|gd7|dx2|bsx|swc", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'snes9x2005_plus': {"display": "Nintendo - SNES / SFC (Snes9x 2005 Plus)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "Non-commercial", "extensions": "smc|fig|sfc|gd3|gd7|dx2|bsx|swc", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'snes9x2010': {"display": "Nintendo - SNES / SFC (Snes9x 2010)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "Non-commercial", "extensions": "smc|fig|sfc|gd3|gd7|dx2|bsx|swc", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'snes9x': {"display": "Nintendo - SNES / SFC (Snes9x)", "system": "Super Nintendo Entertainment System", "manufacturer": "Nintendo", "license": "Non-commercial", "extensions": "smc|sfc|swc|fig|bs|st", "databases": ["Nintendo - Super Nintendo Entertainment System", "Nintendo - Sufami Turbo", "Nintendo - Satellaview"]},
    'squirreljme': {"display": "Java ME (SquirrelJME)", "system": "Java ME", "manufacturer": "Oracle Corporation", "license": "MPL-2.0", "extensions": "jar|sqc|jam|jad|kjx|adf|sec|sto|sp|sp0|sp1|sp2|sp3|sp4|sp5|sp6|sp7|sp8|sp9", "databases": ["J2ME"]},
    'stella2014': {"display": "Atari - 2600 (Stella 2014)", "system": "Atari 2600", "manufacturer": "Atari", "license": "GPLv2", "extensions": "a26|bin", "databases": ["Atari - 2600"]},
    'stella2023': {"display": "Atari - 2600 (Stella 2023)", "system": "Atari 2600", "manufacturer": "Atari", "license": "GPLv2", "extensions": "a26|bin", "databases": ["Atari - 2600"]},
    'stella': {"display": "Atari - 2600 (Stella)", "system": "Atari 2600", "manufacturer": "Atari", "license": "GPLv2", "extensions": "a26|bin", "databases": ["Atari - 2600"]},
    'stonesoup': {"display": "Dungeon Crawl Stone Soup", "license": "GPLv2", "extensions": "crawlrc"},
    'superbroswar': {"display": "Super Bros War", "license": "GPLv2", "extensions": "game"},
    'supermodel': {"display": "Sega - Model 3 (Supermodel)", "system": "Model 3", "manufacturer": "Sega", "license": "GPLv3", "extensions": "zip|chd|7z", "databases": ["Sega - Model 3"]},
    'swanstation': {"display": "Sony - PlayStation (SwanStation)", "system": "PlayStation", "manufacturer": "Sony", "license": "GPLv3", "extensions": "exe|psexe|cue|bin|img|iso|chd|pbp|ecm|mds|psf|m3u", "databases": ["Sony - PlayStation"]},
    'syobonaction': {"display": "Syobon Action", "system": "SyobonAction", "manufacturer": "SyobonAction", "license": "GPLv3+", "databases": ["SyobonAction"]},
    'tamalibretro': {"display": "Bandai - Tamagotchi P1 (TamaLIBretro)", "system": "Tamagotchi P1", "manufacturer": "Bandai", "license": "GPL-2.0", "extensions": "b|bin|rom"},
    'tempgba': {"display": "Nintendo - Game Boy Advance (TempGBA)", "system": "Game Boy Advance", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "gba|bin|agb|gbz", "firmware": ["gba_bios.bin"], "databases": ["Nintendo - Game Boy Advance", "Nintendo - Game Boy Advance (e-Cards)"]},
    'test': {"display": "Test", "license": "MIT"},
    'test_netplay': {"display": "Test for netplay", "system": "Test for netplay"},
    'testaudio_callback': {"display": "TestAudio Callback", "license": "MIT"},
    'testaudio_no_callback': {"display": "TestAudio NoCallback", "license": "MIT"},
    'testaudio_playback_wav': {"display": "TestAudio Playback Wav", "license": "MIT"},
    'testgl_compute_shaders': {"display": "TestGL ComputeShaders", "license": "MIT"},
    'testgl_ff': {"display": "TestGL (FF)", "license": "MIT"},
    'testgl': {"display": "TestGL", "license": "MIT"},
    'testinput_buttontest': {"display": "Button Test", "license": "MIT"},
    'testretroluxury': {"display": "Test RetroLuxury", "license": "Zlib"},
    'testsw': {"display": "TestSW", "license": "MIT"},
    'testsw_vram': {"display": "TestSW VRAM", "license": "MIT"},
    'testvulkan_async_compute': {"display": "TestVulkan AsyncCompute", "license": "MIT"},
    'testvulkan': {"display": "TestVulkan", "license": "MIT"},
    'tgbdual': {"display": "Nintendo - Game Boy / Color (TGB Dual)", "system": "Game Boy/Game Boy Color", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "cgb|dmg|gb|gbc|sgb", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color"]},
    'theodore': {"display": "Thomson - MO/TO (Theodore)", "system": "Thomson MO/TO", "manufacturer": "Thomson", "license": "GPLv3", "extensions": "fd|sap|k7|m7|m5|rom", "databases": ["Thomson - MOTO"]},
    'thepowdertoy': {"display": "The Powder Toy", "system": "Physics Toy", "license": "GPLv3", "extensions": "cps"},
    'tia': {"display": "Atari - 2600 (Tia)", "system": "Atari 2600", "manufacturer": "Atari", "license": "GPLv2+", "extensions": "a26|bin", "databases": ["Atari - 2600"]},
    'tic80': {"display": "TIC-80", "system": "TIC-80", "manufacturer": "TIC-80", "license": "MIT", "extensions": "tic", "databases": ["TIC-80"]},
    'trident': {"display": "Nintendo - 3DS (Trident)", "system": "3DS", "manufacturer": "Nintendo", "license": "GPLv3", "extensions": "3ds|3dsx|elf|axf|cci|cxi|app|ncch", "databases": ["Nintendo - Nintendo 3DS"]},
    'tyrquake': {"display": "Quake (TyrQuake)", "system": "Quake Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pak", "databases": ["Quake"]},
    'uae4arm': {"display": "Commodore - Amiga (UAE4ARM)", "system": "Amiga", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "adf|dms|ipf|adz|wrp|zip|uae|lha|cue|ccd|iso|hdf", "firmware": ["kick34005.A500", "kick40063.A600", "kick40068.A1200", "kick34005.CDTV", "kick40060.CD32", "kick40060.CD32.ext"], "databases": ["Commodore - Amiga", "Commodore - CD32", "Commodore - CDTV"]},
    'ume2015': {"display": "Multi (UME 2015)", "system": "Multi (various)", "manufacturer": "Various", "license": "MAME", "extensions": "zip|chd|7z"},
    'uw8': {"display": "MicroW8", "system": "MicroW8", "license": "The Unlicense", "extensions": "uw8|wasm", "databases": ["MicroW8"]},
    'uxn': {"display": "Uxn / Varvara (zuxn)", "system": "Uxn / Varvara", "manufacturer": "Hundred Rabbits", "license": "MPLv2.0", "extensions": "rom", "databases": ["uxn"]},
    'uzem': {"display": "Uzebox (Uzem)", "system": "Uzebox", "manufacturer": "Uzebox", "license": "MIT", "extensions": "uze", "databases": ["Uzebox"]},
    'vaporspec': {"display": "VaporSpec", "system": "VaporSpec", "manufacturer": "VaporSpec", "license": "MIT", "extensions": "vaporbin", "databases": ["VaporSpec"]},
    'vba_next': {"display": "Nintendo - Game Boy Advance (VBA Next)", "system": "Game Boy Advance", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "gba", "databases": ["Nintendo - Game Boy Advance"]},
    'vbam': {"display": "Nintendo - Game Boy Advance (VBA-M)", "system": "Game Boy/Game Boy Color/Game Boy Advance", "manufacturer": "Nintendo", "license": "GPLv2", "extensions": "dmg|gb|gbc|cgb|sgb|gba", "databases": ["Nintendo - Game Boy", "Nintendo - Game Boy Color", "Nintendo - Game Boy Advance"]},
    'vecx': {"display": "GCE - Vectrex (vecx)", "system": "Vectrex", "manufacturer": "Smith Engineering|General Consumer Electronics", "license": "GPLv3", "extensions": "bin|vec", "databases": ["GCE - Vectrex"]},
    'vemulator': {"display": "VeMUlator", "system": "SEGA Visual Memory Unit", "manufacturer": "Sega", "license": "GPL v3", "extensions": "vms|dci|bin"},
    'vice_x128': {"display": "Commodore - C128 (VICE x128)", "system": "C128", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - 64"]},
    'vice_x64': {"display": "Commodore - C64 (VICE x64, fast)", "system": "C64", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - 64"]},
    'vice_x64dtv': {"display": "Commodore - C64DTV (VICE x64dtv)", "system": "C64DTV", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - 64"]},
    'vice_x64sc': {"display": "Commodore - C64 (VICE x64sc, accurate)", "system": "C64", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - 64"]},
    'vice_xcbm2': {"display": "Commodore - CBM-II 6x0/7x0 (VICE xcbm2)", "system": "CBM-II", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - CBM-II"]},
    'vice_xcbm5x0': {"display": "Commodore - CBM-II 5x0 (VICE xcbm5x0)", "system": "CBM-5x0", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - CBM-5x0"]},
    'vice_xpet': {"display": "Commodore - PET (VICE xpet)", "system": "PET", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - PET"]},
    'vice_xplus4': {"display": "Commodore - PLUS/4 (VICE xplus4)", "system": "PLUS/4", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - Plus-4"]},
    'vice_xscpu64': {"display": "Commodore - C64 SuperCPU (VICE xscpu64)", "system": "C64 SuperCPU", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|/", "databases": ["Commodore - 64"]},
    'vice_xvic': {"display": "Commodore - VIC-20 (VICE xvic)", "system": "VIC-20", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64|g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z|cmd|m3u|vfl|vsf|nib|nbz|d2m|d4m|20|40|60|a0|b0|rom|/", "databases": ["Commodore - VIC-20"]},
    'vidtest': {"display": "VidTest", "license": "GPLv2"},
    'vircon32': {"display": "Vircon32", "system": "Vircon32", "license": "3-clause BSD", "extensions": "v32|V32", "databases": ["Vircon32"]},
    'virtualjaguar': {"display": "Atari - Jaguar (Virtual Jaguar)", "system": "Jaguar", "manufacturer": "Atari", "license": "GPLv3", "extensions": "j64|jag|rom|abs|cof|bin|prg", "databases": ["Atari - Jaguar"]},
    'virtualxt': {"display": "VirtualXT", "system": "PC/XT", "manufacturer": "IBM", "license": "zlib-acknowledgement", "extensions": "img|zip"},
    'vitaquake2-rogue': {"display": "Quake II - Ground Zero (vitaQuake 2 [Rogue])", "system": "Quake II Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pak", "databases": ["Quake II"]},
    'vitaquake2-xatrix': {"display": "Quake II - The Reckoning (vitaQuake 2 [Xatrix])", "system": "Quake II Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pak", "databases": ["Quake II"]},
    'vitaquake2-zaero': {"display": "Quake II - Zaero (vitaQuake 2 [Zaero])", "system": "Quake II Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pak", "databases": ["Quake II"]},
    'vitaquake2': {"display": "Quake II (vitaQuake 2)", "system": "Quake II Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pak", "databases": ["Quake II"]},
    'vitaquake3': {"display": "Quake III: Arena (vitaQuake 3)", "system": "Quake 3 Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pk3", "databases": ["Quake III"]},
    'vitavoyager': {"display": "Star Trek: Voyager - Elite Force (vitaVoyager)", "system": "Quake 3 Game Engine", "manufacturer": "Id Software", "license": "GPLv2", "extensions": "pk3", "databases": ["Quake III"]},
    'wasm4': {"display": "WASM-4", "system": "WASM-4", "license": "ISC", "extensions": "wasm", "databases": ["WASM-4"]},
    'x1': {"display": "Sharp X1 (X Millennium)", "system": "Sharp X1", "manufacturer": "Sharp", "license": "BSD", "extensions": "dx1|zip|2d|2hd|tfd|d88|88d|hdm|xdf|dup|tap|cmd", "databases": ["Sharp - X1"]},
    'x64sdl': {"display": "Commodore - C64 (VICE SDL)", "system": "C64", "manufacturer": "Commodore", "license": "GPLv2", "extensions": "d64|d71|d80|d81|d82|g64||g41|x64|t64|tap|prg|p00|crt|bin|zip|gz|d6z|d7z|d8z|g6z|g4z|x6z", "databases": ["Commodore - 64"]},
    'xrick': {"display": "Rick Dangerous (XRick)", "system": "Rick Dangerous Game Engine", "license": "GPLv3", "extensions": "zip", "databases": ["Rick Dangerous"]},
    'yabasanshiro': {"display": "Sega - Saturn (YabaSanshiro)", "system": "Saturn", "manufacturer": "Sega", "license": "GPLv2", "extensions": "bin|ccd|chd|cue|iso|mds|zip", "firmware": ["saturn_bios.bin"], "databases": ["Sega - Saturn"]},
    'yabause': {"display": "Sega - Saturn (Yabause)", "system": "Saturn", "manufacturer": "Sega", "license": "GPLv2", "extensions": "bin|ccd|chd|cue|iso|mds|zip|m3u", "databases": ["Sega - Saturn"]},
    'ymir': {"display": "Sega - Saturn (Ymir)", "system": "Saturn", "manufacturer": "Sega", "license": "GPLv3", "extensions": "cue|chd|mds|ccd|iso|m3u", "databases": ["Sega - Saturn"]},
}


def info_for(core_id: str) -> dict:
    """What libretro says about this core, or an empty dict.

    Empty is a fact about the table, never an instruction to substitute
    something. Callers leave the field unset rather than filling it in --
    a plausible-looking guess in a column an operator reads while choosing
    is worse than a blank.
    """
    if not isinstance(core_id, str):
        return {}
    return CORE_INFO.get(core_id.strip(), {})


def system_for(core_id: str) -> str | None:
    """The system a core emulates, or None when libretro does not say."""
    return info_for(core_id).get("system") or None


def matches_system(core_id: str, needle: str) -> bool:
    """True when `needle` appears in anything this core says it is for.

    Matched against the system name, the manufacturer and every libretro
    database name, case-insensitively, because an operator types "snes"
    or "PlayStation" rather than "Super Nintendo Entertainment System" --
    and because a core's database names are where the cross-platform cases
    live: Snes9x names "Nintendo - Sufami Turbo" and "Nintendo -
    Satellaview" alongside the SNES itself.
    """
    needle = (needle or "").strip().casefold()
    if not needle:
        return True
    row = info_for(core_id)
    haystacks = [
        row.get("system", ""),
        row.get("manufacturer", ""),
        row.get("display", ""),
        *row.get("databases", []),
    ]
    return any(needle in h.casefold() for h in haystacks)

