"""Regenerate docs/PLUGINS.md from catalog/plugins.json.

The table is generated rather than hand-edited so the published directory and
the machine-readable catalog cannot drift apart -- a wiki page that disagrees
with what the CLI installs is worse than no page at all. test_directory_is_in_sync
fails if this has not been re-run after a catalog change.

    python scripts/render_directory.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rom_hub.catalog import load_catalog, render_markdown  # noqa: E402

CATALOG = ROOT / "catalog" / "plugins.json"
OUT = ROOT / "docs" / "PLUGINS.md"

PREAMBLE = """<!-- Generated by scripts/render_directory.py. Do not edit by hand. -->
# Unofficial ROM Hub plugins

A community-kept directory of RPP v1 sources: the community publishes plugins,
this lists where to find them, and you choose what to install.

## Read first

A plugin is a Python package written by somebody else. In most plugin systems
that sentence is the end of the security discussion, because a plugin is
imported into the host and runs with the full privileges of the process that
loaded it — its author's code becomes your code.

**ROM Hub is built the other way round, and the difference is the point of the
project.** A plugin runs as its own subprocess with:

- no RomM token,
- no filesystem mount,
- and no network sockets of its own.

Its only route outward is `ctx.http`, an RPC back to the host, which checks the
URL against the allowlist that plugin declared in its `manifest.toml` **before**
opening a connection. A plugin that asks for a host it did not declare is
refused, and the request never reaches the network.

That is a real boundary, but it is not a sandbox for everything. Still true:

- A plugin runs **arbitrary code** in that subprocess. It can burn CPU, and it
  can do anything permitted inside its own process.
- It sees the **config you give it** and the queries you run.
- It can reach **any host it declared**, and the `Network` column below is
  exactly that declaration. Read it before installing. A search plugin asking
  for hosts unrelated to its source is the thing to be suspicious of.
- Memory is **not** capped in Phase 1 (`setrlimit` is POSIX-only); the wall-clock
  timeout and output-size cap are.

**This directory grants nothing.** It records where a plugin lives. The
permissions come from the plugin's own manifest, read at install time — so a
compromised directory cannot widen what an installed plugin may reach.
`test_catalog_cannot_widen_permissions` pins that: the broker reads
`manifest.network` and never consults the catalog at all.

### What the sandbox does and does not cover

Worth being exact, because "sandboxed" is doing less work than it sounds:

- **The broker enforces the network allowlist.** Every URL — including each
  hop of a redirect, and including URLs the plugin returns in a `FetchPlan`
  for the *host* to fetch — is checked against the plugin's declared hosts
  before a socket is opened.
- **On Linux, seccomp confines the plugin.** The subprocess installs the
  filter on itself before importing any plugin code, so network egress and
  process spawn are blocked outright rather than merely disallowed.
- **File reads are NOT confined.** seccomp cannot filter on a path. A plugin
  can read any file the Hub process can read. This is the real limit of the
  boundary, and no plugin in this directory changes it.
- **Windows cannot sandbox at all.** There is no confinement available, so
  plugins refuse to run unless `ROM_HUB_ALLOW_UNSANDBOXED=1` is set. With it
  set there is none of the above: a hostile plugin can ignore the allowlist,
  open its own sockets, read any readable file, and spawn processes.
- Memory is **not** capped in Phase 1 (`setrlimit` is POSIX-only); the
  wall-clock timeout and output-size cap are.

**Install only plugins you trust.** The allowlist tells you what a plugin
*asks for*; on Linux it is also what it is held to.

## Which backends a plugin works against

**Every plugin here is portable, and that is not the same as every plugin
being useful everywhere.** A plugin never talks to a library server. It
returns a *description* — a `FetchPlan`, a `MetadataPatch` — and the host
executes it against whichever backend `ROM_HUB_BACKEND` selects. Nothing in a
plugin has ever known which server is on the other side.

What the *backend* decides is whether that description can be carried out.
The three supported servers do not do the same things:

| | RomM | Gaseous | Retrom |
|---|---|---|---|
| `import` (upload + list) | yes | yes | yes |
| `scan` (post-upload registration) | yes | yes | yes |
| `metadata` (write a rom's fields) | yes | **no** | yes |
| `artwork` (store a cover) | yes | **no** | yes |
| `collections` (group roms) | yes | **no** | **no** |

So a `metadata` plugin does nothing useful against Gaseous, and the Hub says
so up front rather than fetching a cover it cannot store: writing nothing is
not a degraded write. An `importer` plugin that files its results under a
collection (archive-org defaults to "Archive.org") *does* still import against
a backend with no collections, with the grouping skipped and reported —
because the ROM is the job and the collection is a nicety on top. The rule is
per capability, not per plugin, and it lives in `README.md` under
*Cannot-do-the-job vs cannot-do-an-extra*.

The **Backends** column below applies that rule to each plugin's declared
capabilities. It is generated from the two declarations — the plugin's and the
backend's — so it cannot drift out of step with either.

## Every plugin listed here is published

Each of the seven below lives in its own public repository, and every
`repository`, `install` and `download` URL on this page resolves. Nothing here
is a placeholder any more.

They also have a **development copy** in this repository's `plugins-dev/`
directory, which is what the offline test suite runs against. The published
repository at the pinned tag is **canonical**: if the two ever disagree, the
tag is right and the copy is stale. `plugins-dev/README.md` says how they are
kept in step and how to check.

## Installing

    rom-hub plugin browse                # list what's here
    rom-hub plugin install archive-org   # by slug, resolved through this directory
    rom-hub plugin install https://github.com/BlizzHacker/rom-hub-archive-org --ref v0.2.0

Installing by slug takes the repository **and** the tag from this directory, so
the two forms above fetch the same commit — which the Hub then records as a
resolved SHA, because a tag can be moved after you install it.

Every install is pinned to a tag, never a branch. Updating is deliberate — you
re-run `install` with a new ref — so a plugin cannot quietly change under you,
and neither can this directory change it for you.

## Status

| | meaning |
|---|---|
| ✔ | working against the current host |
| ❗ | works with caveats, see comments |
| ✖ | known broken |

## Plugins

"""

FOOTER = """

## Adding your plugin

Open a pull request adding an entry to
[`catalog/plugins.json`](../catalog/plugins.json), then run
`python scripts/render_directory.py` to regenerate this page. An entry must:

- point `repository`, `install` and `download` at **https** URLs;
- pin `download` to the exact tag named in `ref` — a moving branch would mean
  a later install silently ships different code;
- declare `rpp_version` `"1"`;
- list the `network` hosts your `manifest.toml` actually requests, so a reader
  can judge the ask before installing;
- carry a one-line `description` and a `terms` paragraph stating **your
  source's** licensing position in plain language — not your plugin's own
  licence, which is its `LICENSE` file. A directory that says where to get
  ROMs and stays quiet about whether they may lawfully be got is doing half
  the job;
- set `search_only` if your importer cannot complete — it renders as "cannot
  import", because a plugin can implement `metadata` and still never fetch a
  file — and `key_required` if
  the plugin is useless without a credential. Both are things a reader needs
  before installing, not after filing a bug;
- leave `in_tree` `false` unless your plugin has **no** published repository
  and can only be installed from a path inside this tree. Every plugin listed
  today has one, so every entry is `false`; the flag exists so that a
  not-yet-published plugin renders the path that works instead of a link that
  404s.

The catalog is validated on load, so a malformed entry fails the test suite
rather than reaching a user. `terms` and `description` must be non-empty: a
blank cell reads like "nothing to declare" rather than "nobody filled this
in".
"""


def main() -> int:
    entries = load_catalog(CATALOG)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        PREAMBLE + render_markdown(entries) + FOOTER, encoding="utf-8", newline="\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} plugin(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
