"""Regenerate docs/PLUGINS.md from catalog/plugins.json.

The table is generated rather than hand-edited so the published directory and
the machine-readable catalog cannot drift apart -- a wiki page that disagrees
with what the CLI installs is worse than no page at all. test_directory_is_in_sync
fails if this has not been re-run after a catalog change.

    python scripts/render_directory.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from romm_hub.catalog import load_catalog, render_markdown  # noqa: E402

CATALOG = ROOT / "catalog" / "plugins.json"
OUT = ROOT / "docs" / "PLUGINS.md"

PREAMBLE = """<!-- Generated by scripts/render_directory.py. Do not edit by hand. -->
# Unofficial RomM Hub plugins

A directory of RPP v1 sources, in the spirit of qBittorrent's
[unofficial search plugins](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins)
page: the community publishes plugins, this lists where to find them, and you
choose what to install.

## Read first

qBittorrent's page warns that "Python plugins/scripts are, by its nature, not
considered to be safe". That is true there because a qBittorrent plugin runs
with the full privileges of the process that loads it.

**RomM Hub is built the other way round, and the difference is the point of the
project.** A plugin runs as its own subprocess with:

- no RomM token,
- no filesystem mount,
- and no network sockets of its own.

Its only route outward is `ctx.http`, an RPC back to the host, which checks the
URL against the allowlist that plugin declared in its `manifest.toml` **before**
opening a connection. A plugin that asks for a host it did not declare is
refused, and the request never reaches the network.

That is a real boundary, but it is not a sandbox for everything. Still true:

- A plugin runs **arbitrary code** in that subprocess. It can burn CPU, and it
  can do anything permitted inside its own process.
- It sees the **config you give it** and the queries you run.
- It can reach **any host it declared**, and the `Network` column below is
  exactly that declaration. Read it before installing. A search plugin asking
  for hosts unrelated to its source is the thing to be suspicious of.
- Memory is **not** capped in Phase 1 (`setrlimit` is POSIX-only); the wall-clock
  timeout and output-size cap are.

**This directory grants nothing.** It records where a plugin lives. The
permissions come from the plugin's own manifest, read at install time — so a
compromised directory cannot widen what an installed plugin may reach.
`test_catalog_cannot_widen_permissions` pins that: the broker reads
`manifest.network` and never consults the catalog at all.

### What the sandbox does and does not cover

Worth being exact, because "sandboxed" is doing less work than it sounds:

- **The broker enforces the network allowlist.** Every URL — including each
  hop of a redirect, and including URLs the plugin returns in a `FetchPlan`
  for the *host* to fetch — is checked against the plugin's declared hosts
  before a socket is opened.
- **On Linux, seccomp confines the plugin.** The subprocess installs the
  filter on itself before importing any plugin code, so network egress and
  process spawn are blocked outright rather than merely disallowed.
- **File reads are NOT confined.** seccomp cannot filter on a path. A plugin
  can read any file the Hub process can read. This is the real limit of the
  boundary, and no plugin in this directory changes it.
- **Windows cannot sandbox at all.** There is no confinement available, so
  plugins refuse to run unless `ROMM_HUB_ALLOW_UNSANDBOXED=1` is set. With it
  set there is none of the above: a hostile plugin can ignore the allowlist,
  open its own sockets, read any readable file, and spawn processes.
- Memory is **not** capped in Phase 1 (`setrlimit` is POSIX-only); the
  wall-clock timeout and output-size cap are.

**Install only plugins you trust.** The allowlist tells you what a plugin
*asks for*; on Linux it is also what it is held to.

## These plugins ship in-tree

The six plugins below live in this repository's `plugins-dev/` directory and
**have no individual public repositories yet**. Rather than print URLs that do
not resolve, their repository and download fields use the reserved
`.invalid` TLD (RFC 2606, guaranteed never to resolve) — if you see
`romm-hub.invalid`, that is a placeholder saying "not published yet", not a
link to follow. Install them by path:

    romm-hub plugin install ./plugins-dev/archive-org

Note that `plugin install` clones its source, so each plugin directory has to
be a git repository for that to work.

## Installing

    romm-hub plugin browse                 # list what's here
    romm-hub plugin install ./plugins-dev/archive-org   # in-tree, today
    romm-hub plugin install https://github.com/someone/their-plugin --ref v1.2.0

Installs from a URL are pinned to a tag. Updating is deliberate — re-run
`install` with a new ref — so a plugin cannot quietly change under you.

## Status

| | meaning |
|---|---|
| ✔ | working against the current host |
| ❗ | works with caveats, see comments |
| ✖ | known broken |

## Plugins

"""

FOOTER = """

## Adding your plugin

Open a pull request adding an entry to
[`catalog/plugins.json`](../catalog/plugins.json), then run
`python scripts/render_directory.py` to regenerate this page. An entry must:

- point `repository`, `install` and `download` at **https** URLs;
- pin `download` to the exact tag named in `ref` — a moving branch would mean
  a later install silently ships different code;
- declare `rpp_version` `"1"`;
- list the `network` hosts your `manifest.toml` actually requests, so a reader
  can judge the ask before installing;
- carry a one-line `description` and a `terms` paragraph stating **your
  source's** licensing position in plain language — not your plugin's own
  licence, which is its `LICENSE` file. A directory that says where to get
  ROMs and stays quiet about whether they may lawfully be got is doing half
  the job;
- set `search_only` if your importer cannot complete, and `key_required` if
  the plugin is useless without a credential. Both are things a reader needs
  before installing, not after filing a bug;
- set `in_tree` only if the plugin ships inside this repository.

The catalog is validated on load, so a malformed entry fails the test suite
rather than reaching a user. `terms` and `description` must be non-empty: a
blank cell reads like "nothing to declare" rather than "nobody filled this
in".
"""


def main() -> int:
    entries = load_catalog(CATALOG)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        PREAMBLE + render_markdown(entries) + FOOTER, encoding="utf-8", newline="\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} plugin(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
